### ISSUE TITLE
rust on gentoo-musl with clang default-libcxx use flag

### ISSUE THREAD

**Issue by BeanieBen9990** [12101111/overlay#11]
I'm trying to install a gentoo-musl system with clang as a main compiler. However, emerging rust on a musl libc system causes it to pull in libunwind as a dependency which blocks llvm-libunwind, which is pulled by clang when the default-libcxx use flag is enabled, to use the libc++ standard library from llvm. I was wondering if the rust ebuild on this overlay fixes this issue. Thanks!

**Comment by 12101111** [comment]
This ebuild support llvm-libunwind, and link to system llvm-libunwind by this patch: https://github.com/12101111/overlay/blob/master/dev-lang/rust/files/musl-use-external-libunwind.patch
But rust 1.49.0 has official support to link against system libunwind: https://github.com/rust-lang/rust/blob/stable/config.toml.example#L533, so this patch is no longer needed for next version.

**Comment by BeanieBen9990** [comment]
Got it working with that change to the ebuild and that patch. Didn't need any of the other changes, so I just made a local overlay with those changes. Thanks! I have another question about working with rust on musl though. What's your rustc target? I'm having trouble emerging spidermonkey and my target was one of the issues

**Comment by 12101111** [comment]
You also need change `elibc_musl? ( sys-libs/libunwind:= )` to `elibc_musl? ( || ( sys-libs/llvm-libunwind sys-libs/libunwind:= ) )`  and remove `"${FILESDIR}"/1.48.0-gentoo-musl-target-specs.patch` in ebuild
The target is x86_64-unknown-linux-musl.

**Comment by BeanieBen9990** [comment]
In spidermonkey?

**Comment by BeanieBen9990** [comment]
Yeah I did that for rust. Ended up with spidermonkey failing because it was compiling for target x86_64-gentoo-linux-musl and I manually changed it to x86_64-unknown-linux-musl in the spidermonkey ebuild, but it's now failing with a relocation error. Do you have spidermonkey working on your system?

**Comment by BeanieBen9990** [comment]
Ok I've taken a better look at the repo and saw that your polkit overlay removes that dependency and instead uses duktape. I think I'm going to use that instead of pulling my hair out with spidermonkey. Thanks!

**Comment by BeanieBen9990** [comment]
Actually I ended up getting spidermonkey to compile. I think it was the musl-fix-linux_musl_base.patch that did it for me but I'm not totally sure.

**Comment by OlehVinichenko** [comment]
when, having complete llm/clang with lbcxx, rust from your overlay is sitll trying to link against libgcc_s. I tried ebuild as is
with USE="default-libcxx system-llvm", no rust installed before
    
 Running `/var/src/build/portage/dev-lang/rust-1.48.0/work/rust-stage0/bin/rustc --crate-name build_script_build /var/src/build/portage/dev-lang/rust-1.48.0/work/rustc-1.48.0-src/vendor/memchr/build.rs --error-format=json --json=diagnostic-rendered-ansi --crate-type bin --emit=dep-info,link -C embed-bitcode=no -C debuginfo=2 --cfg 'feature="default"' --cfg 'feature="std"' --cfg 'feature="use_std"' -C metadata=fee8eed40cf0f418 -C extra-filename=-fee8eed40cf0f418 --out-dir /var/src/build/portage/dev-lang/rust-1.48.0/work/rustc-1.48.0-src/build/bootstrap/debug/build/memchr-fee8eed40cf0f418 -L dependency=/var/src/build/portage/dev-lang/rust-1.48.0/work/rustc-1.48.0-src/build/bootstrap/debug/deps --cap-lints allow -Lnative=/usr/lib/llvm/11/lib -Cdebuginfo=2 -C target-feature=-crt-static -C linker=x86_64-gentoo-linux-musl-clang -Wrust_2018_idioms -Wunused_lifetimes -Dwarnings`
     Running `/var/src/build/portage/dev-lang/rust-1.48.0/work/rust-stage0/bin/rustc --crate-name build_script_build /var/src/build/portage/dev-lang/rust-1.48.0/work/rustc-1.48.0-src/vendor/serde_derive-1.0.115/build.rs --error-format=json --json=diagnostic-rendered-ansi --crate-type bin --emit=dep-info,link -C embed-bitcode=no -C debuginfo=2 --cfg 'feature="default"' -C metadata=03b92208e2277120 -C extra-filename=-03b92208e2277120 --out-dir /var/src/build/portage/dev-lang/rust-1.48.0/work/rustc-1.48.0-src/build/bootstrap/debug/build/serde_derive-03b92208e2277120 -L dependency=/var/src/build/portage/dev-lang/rust-1.48.0/work/rustc-1.48.0-src/build/bootstrap/debug/deps --cap-lints allow -Lnative=/usr/lib/llvm/11/lib -Cdebuginfo=2 -C target-feature=-crt-static -C linker=x86_64-gentoo-linux-musl-clang -Wrust_2018_idioms -Wunused_lifetimes -Dwarnings`
     Running `/var/src/build/portage/dev-lang/rust-1.48.0/work/rust-stage0/bin/rustc --crate-name lazy_static /var/src/build/portage/dev-lang/rust-1.48.0/work/rustc-1.48.0-src/vendor/lazy_static/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts --crate-type lib --emit=dep-info,metadata,link -C embed-bitcode=no -C debuginfo=2 -C metadata=49e27f62894f48e1 -C extra-filename=-49e27f62894f48e1 --out-dir /var/src/build/portage/dev-lang/rust-1.48.0/work/rustc-1.48.0-src/build/bootstrap/debug/deps -L dependency=/var/src/build/portage/dev-lang/rust-1.48.0/work/rustc-1.48.0-src/build/bootstrap/debug/deps --cap-lints allow -Lnative=/usr/lib/llvm/11/lib -Cdebuginfo=2 -C target-feature=-crt-static -C linker=x86_64-gentoo-linux-musl-clang -Wrust_2018_idioms -Wunused_lifetimes -Dwarnings`
   Compiling libc v0.2.77
     Running `/var/src/build/portage/dev-lang/rust-1.48.0/work/rust-stage0/bin/rustc --crate-name build_script_build /var/src/build/portage/dev-lang/rust-1.48.0/work/rustc-1.48.0-src/vendor/libc/build.rs --error-format=json --json=diagnostic-rendered-ansi --crate-type bin --emit=dep-info,link -C embed-bitcode=no -C debuginfo=2 --cfg 'feature="default"' --cfg 'feature="std"' -C metadata=4e269a19a361d876 -C extra-filename=-4e269a19a361d876 --out-dir /var/src/build/portage/dev-lang/rust-1.48.0/work/rustc-1.48.0-src/build/bootstrap/debug/build/libc-4e269a19a361d876 -L dependency=/var/src/build/portage/dev-lang/rust-1.48.0/work/rustc-1.48.0-src/build/bootstrap/debug/deps --cap-lints allow -Lnative=/usr/lib/llvm/11/lib -Cdebuginfo=2 -C target-feature=-crt-static -C linker=x86_64-gentoo-linux-musl-clang -Wrust_2018_idioms -Wunused_lifetimes -Dwarnings`
   Compiling cfg-if v0.1.10
     Running `/var/src/build/portage/dev-lang/rust-1.48.0/work/rust-stage0/bin/rustc --crate-name cfg_if --edition=2018 /var/src/build/portage/dev-lang/rust-1.48.0/work/rustc-1.48.0-src/vendor/cfg-if/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts --crate-type lib --emit=dep-info,metadata,link -C embed-bitcode=no -C debuginfo=2 -C metadata=1dae826d0f4a35c8 -C extra-filename=-1dae826d0f4a35c8 --out-dir /var/src/build/portage/dev-lang/rust-1.48.0/work/rustc-1.48.0-src/build/bootstrap/debug/deps -L dependency=/var/src/build/portage/dev-lang/rust-1.48.0/work/rustc-1.48.0-src/build/bootstrap/debug/deps --cap-lints allow -Lnative=/usr/lib/llvm/11/lib -Cdebuginfo=2 -C target-feature=-crt-static -C linker=x86_64-gentoo-linux-musl-clang -Wrust_2018_idioms -Wunused_lifetimes -Dwarnings`
   Compiling log v0.4.11
     Running `/var/src/build/portage/dev-lang/rust-1.48.0/work/rust-stage0/bin/rustc --crate-name build_script_build /var/src/build/portage/dev-lang/rust-1.48.0/work/rustc-1.48.0-src/vendor/log/build.rs --error-format=json --json=diagnostic-rendered-ansi --crate-type bin --emit=dep-info,link -C embed-bitcode=no -C debuginfo=2 -C metadata=e80dc239645548b2 -C extra-filename=-e80dc239645548b2 --out-dir /var/src/build/portage/dev-lang/rust-1.48.0/work/rustc-1.48.0-src/build/bootstrap/debug/build/log-e80dc239645548b2 -L dependency=/var/src/build/portage/dev-lang/rust-1.48.0/work/rustc-1.48.0-src/build/bootstrap/debug/deps --cap-lints allow -Lnative=/usr/lib/llvm/11/lib -Cdebuginfo=2 -C target-feature=-crt-static -C linker=x86_64-gentoo-linux-musl-clang -Wrust_2018_idioms -Wunused_lifetimes -Dwarnings`
error: linking with `x86_64-gentoo-linux-musl-clang` failed: exit code: 1

**Comment by OlehVinichenko** [comment]
Compiling log v0.4.11
     Running `/var/src/build/portage/dev-lang/rust-1.48.0/work/rust-stage0/bin/rustc --crate-name build_script_build /var/src/build/portage/dev-lang/rust-1.48.0/work/rustc-1.48.0-src/vendor/log/build.rs --error-format=json --json=diagnostic-rendered-ansi --crate-type bin --emit=dep-info,link -C embed-bitcode=no -C debuginfo=2 -C metadata=e80dc239645548b2 -C extra-filename=-e80dc239645548b2 --out-dir /var/src/build/portage/dev-lang/rust-1.48.0/work/rustc-1.48.0-src/build/bootstrap/debug/build/log-e80dc239645548b2 -L dependency=/var/src/build/portage/dev-lang/rust-1.48.0/work/rustc-1.48.0-src/build/bootstrap/debug/deps --cap-lints allow -Lnative=/usr/lib/llvm/11/lib -Cdebuginfo=2 -C target-feature=-crt-static -C linker=x86_64-gentoo-linux-musl-clang -Wrust_2018_idioms -Wunused_lifetimes -Dwarnings`
error: linking with `x86_64-gentoo-linux-musl-clang` failed: exit code: 1
  |
  = note: "x86_64-gentoo-linux-musl-clang" "-Wl,--as-needed" "-Wl,-z,noexecstack" "-m64" "-Wl,--eh-frame-hdr" "-L" "/var/src/build/portage/dev-lang/rust-1.48.0/work/rust-stage0/lib/rustlib/x86_64-unknown-linux-musl/lib" "/var/src/build/portage/dev-lang/rust-1.48.0/work/rustc-1.48.0-src/build/bootstrap/debug/build/memchr-fee8eed40cf0f418/build_script_build-fee8eed40cf0f418.build_script_build.6jc0fph1-cgu.0.rcgu.o" "/var/src/build/portage/dev-lang/rust-1.48.0/work/rustc-1.48.0-src/build/bootstrap/debug/build/memchr-fee8eed40cf0f418/build_script_build-fee8eed40cf0f418.build_script_build.6jc0fph1-cgu.1.rcgu.o" "/var/src/build/portage/dev-lang/rust-1.48.0/work/rustc-1.48.0-src/build/bootstrap/debug/build/memchr-fee8eed40cf0f418/build_script_build-fee8eed40cf0f418.build_script_build.6jc0fph1-cgu.10.rcgu.o" "/var/src/build/portage/dev-lang/rust-1.48.0/work/rustc-1.48.0-src/build/bootstrap/debug/build/memchr-fee8eed40cf0f418/build_script_build-fee8eed40cf0f418.build_script_build.6jc0fph1-cgu.11.rcgu.o" "/var/src/build/portage/dev-lang/rust-1.48.0/work/rustc-1.48.0-src/build/bootstrap/debug/build/memchr-fee8eed40cf0f418/build_script_build-fee8eed40cf0f418.build_script_build.6jc0fph1-cgu.12.rcgu.o" "/var/src/build/portage/dev-lang/rust-1.48.0/work/rustc-1.48.0-src/build/bootstrap/debug/build/memchr-fee8eed40cf0f418/build_script_build-fee8eed40cf0f418.build_script_build.6jc0fph1-cgu.13.rcgu.o" "/var/src/build/portage/dev-lang/rust-1.48.0/work/rustc-1.48.0-src/build/bootstrap/debug/build/memchr-fee8eed40cf0f418/build_script_build-fee8eed40cf0f418.build_script_build.6jc0fph1-cgu.14.rcgu.o" "/var/src/build/portage/dev-lang/rust-1.48.0/work/rustc-1.48.0-src/build/bootstrap/debug/build/memchr-fee8eed40cf0f418/build_script_build-fee8eed40cf0f418.build_script_build.6jc0fph1-cgu.15.rcgu.o" "/var/src/build/portage/dev-lang/rust-1.48.0/work/rustc-1.48.0-src/build/bootstrap/debug/build/memchr-fee8eed40cf0f418/build_script_build-fee8eed40cf0f418.build_script_build.6jc0fph1-cgu.2.rcgu.o" "/var/src/build/portage/dev-lang/rust-1.48.0/work/rustc-1.48.0-src/build/bootstrap/debug/build/memchr-fee8eed40cf0f418/build_script_build-fee8eed40cf0f418.build_script_build.6jc0fph1-cgu.3.rcgu.o" "/var/src/build/portage/dev-lang/rust-1.48.0/work/rustc-1.48.0-src/build/bootstrap/debug/build/memchr-fee8eed40cf0f418/build_script_build-fee8eed40cf0f418.build_script_build.6jc0fph1-cgu.4.rcgu.o" "/var/src/build/portage/dev-lang/rust-1.48.0/work/rustc-1.48.0-src/build/bootstrap/debug/build/memchr-fee8eed40cf0f418/build_script_build-fee8eed40cf0f418.build_script_build.6jc0fph1-cgu.5.rcgu.o" "/var/src/build/portage/dev-lang/rust-1.48.0/work/rustc-1.48.0-src/build/bootstrap/debug/build/memchr-fee8eed40cf0f418/build_script_build-fee8eed40cf0f418.build_script_build.6jc0fph1-cgu.6.rcgu.o" "/var/src/build/portage/dev-lang/rust-1.48.0/work/rustc-1.48.0-src/build/bootstrap/debug/build/memchr-fee8eed40cf0f418/build_script_build-fee8eed40cf0f418.build_script_build.6jc0fph1-cgu.7.rcgu.o" "/var/src/build/portage/dev-lang/rust-1.48.0/work/rustc-1.48.0-src/build/bootstrap/debug/build/memchr-fee8eed40cf0f418/build_script_build-fee8eed40cf0f418.build_script_build.6jc0fph1-cgu.8.rcgu.o" "/var/src/build/portage/dev-lang/rust-1.48.0/work/rustc-1.48.0-src/build/bootstrap/debug/build/memchr-fee8eed40cf0f418/build_script_build-fee8eed40cf0f418.build_script_build.6jc0fph1-cgu.9.rcgu.o" "-o" "/var/src/build/portage/dev-lang/rust-1.48.0/work/rustc-1.48.0-src/build/bootstrap/debug/build/memchr-fee8eed40cf0f418/build_script_build-fee8eed40cf0f418" "/var/src/build/portage/dev-lang/rust-1.48.0/work/rustc-1.48.0-src/build/bootstrap/debug/build/memchr-fee8eed40cf0f418/build_script_build-fee8eed40cf0f418.ecuiwh53v65t0vs.rcgu.o" "-Wl,--gc-sections" "-pie" "-Wl,-zrelro" "-Wl,-znow" "-nodefaultlibs" "-L" "/var/src/build/portage/dev-lang/rust-1.48.0/work/rustc-1.48.0-src/build/bootstrap/debug/deps" "-L" "/usr/lib/llvm/11/lib" "-L" "/var/src/build/portage/dev-lang/rust-1.48.0/work/rust-stage0/lib/rustlib/x86_64-unknown-linux-musl/lib" "-Wl,--start-group" "-Wl,-Bstatic" "/var/src/build/portage/dev-lang/rust-1.48.0/work/rust-stage0/lib/rustlib/x86_64-unknown-linux-musl/lib/libstd-bee2828aa55ce985.rlib" "/var/src/build/portage/dev-lang/rust-1.48.0/work/rust-stage0/lib/rustlib/x86_64-unknown-linux-musl/lib/libpanic_unwind-a46019870feeda75.rlib" "/var/src/build/portage/dev-lang/rust-1.48.0/work/rust-stage0/lib/rustlib/x86_64-unknown-linux-musl/lib/libminiz_oxide-aced41aae987f322.rlib" "/var/src/build/portage/dev-lang/rust-1.48.0/work/rust-stage0/lib/rustlib/x86_64-unknown-linux-musl/lib/libadler-7ea2f38336caa555.rlib" "/var/src/build/portage/dev-lang/rust-1.48.0/work/rust-stage0/lib/rustlib/x86_64-unknown-linux-musl/lib/libobject-91dcb508d5222e91.rlib" "/var/src/build/portage/dev-lang/rust-1.48.0/work/rust-stage0/lib/rustlib/x86_64-unknown-linux-musl/lib/libaddr2line-5fe4d6e14de2449b.rlib" "/var/src/build/portage/dev-lang/rust-1.48.0/work/rust-stage0/lib/rustlib/x86_64-unknown-linux-musl/lib/libgimli-3e9698690a9f2e60.rlib" "/var/src/build/portage/dev-lang/rust-1.48.0/work/rust-stage0/lib/rustlib/x86_64-unknown-linux-musl/lib/librustc_demangle-fdeb48d50cd1e035.rlib" "/var/src/build/portage/dev-lang/rust-1.48.0/work/rust-stage0/lib/rustlib/x86_64-unknown-linux-musl/lib/libhashbrown-8cdefe25835d9c06.rlib" "/var/src/build/portage/dev-lang/rust-1.48.0/work/rust-stage0/lib/rustlib/x86_64-unknown-linux-musl/lib/librustc_std_workspace_alloc-a355fc2907d3ec69.rlib" "/var/src/build/portage/dev-lang/rust-1.48.0/temp/rustcRfo4wS/libunwind-58613a4e7a39d717.rlib" "/var/src/build/portage/dev-lang/rust-1.48.0/work/rust-stage0/lib/rustlib/x86_64-unknown-linux-musl/lib/libcfg_if-22dd506f93a16571.rlib" "/var/src/build/portage/dev-lang/rust-1.48.0/temp/rustcRfo4wS/liblibc-3f976098fb47fc81.rlib" "/var/src/build/portage/dev-lang/rust-1.48.0/work/rust-stage0/lib/rustlib/x86_64-unknown-linux-musl/lib/liballoc-63634bbb48face34.rlib" "/var/src/build/portage/dev-lang/rust-1.48.0/work/rust-stage0/lib/rustlib/x86_64-unknown-linux-musl/lib/librustc_std_workspace_core-72b21bbacc940957.rlib" "/var/src/build/portage/dev-lang/rust-1.48.0/work/rust-stage0/lib/rustlib/x86_64-unknown-linux-musl/lib/libcore-af27050a29685aa2.rlib" "-Wl,--end-group" "/var/src/build/portage/dev-lang/rust-1.48.0/work/rust-stage0/lib/rustlib/x86_64-unknown-linux-musl/lib/libcompiler_builtins-c4dd499bf25e769d.rlib" "-Wl,-Bdynamic" "-lgcc_s" "-lc"
  = note: ld.lld: error: unable to find library -lgcc_s
          clang-11: error: linker command failed with exit code 1 (use -v to see invocation)


error: linking with `x86_64-gentoo-linux-musl-clang` failed: exit code: 1

**Comment by BeanieBen9990** [comment]
> You also need change `elibc_musl? ( sys-libs/libunwind:= )` to `elibc_musl? ( || ( sys-libs/llvm-libunwind sys-libs/libunwind:= ) )`  and remove `"${FILESDIR}"/1.48.0-gentoo-musl-target-specs.patch` in ebuild
> 
> The target is x86_64-unknown-linux-musl.

Is there a way to keep it using x86_64-gentoo-linux-musl? I'm asking because I had to patch spidermonkey with this new "unknown" target instead of the default "gentoo" one and I would love to have less overlays and patches needed for the packages.

**Comment by LinuxUserGD** [comment]
> > You also need change `elibc_musl? ( sys-libs/libunwind:= )` to `elibc_musl? ( || ( sys-libs/llvm-libunwind sys-libs/libunwind:= ) )`  and remove `"${FILESDIR}"/1.48.0-gentoo-musl-target-specs.patch` in ebuild
> > The target is x86_64-unknown-linux-musl.
> 
> Is there a way to keep it using x86_64-gentoo-linux-musl? I'm asking because I had to patch spidermonkey with this new "unknown" target instead of the default "gentoo" one and I would love to have less overlays and patches needed for the packages.

Compiling firefox with rust and gcc works fine. Just enable `rust-bootstrap` useflag and eselect rust-bin target from main gentoo repo when compiling rust from this overlay.
