### ISSUE TITLE
dev-qt/qtwebengine strncpy not declared in this scope

### ISSUE THREAD

**Issue by jakelyz** [12101111/overlay#14]
Hey, thanks for providing the overlay. It helped immensely in getting qtwebengine to build, and subsequently Otter.

I noticed during qtwebengine compilation, it would fail due to an error similar to "strncpy was not declared in this scope", stemming from named_platform_channel_posix.cc. Have you noticed this on your system? That was the only issue I noticed, and [this patch](https://github.com/void-linux/void-packages/blob/master/srcpkgs/qt5-webengine/patches/0001-mus-cstring.patch) fixes it. Sorry for not having the actual failure logs, I can re-create if needed.

**Comment by 12101111** [comment]
I use libc++ in my system and don't have this issue.

**Comment by jakelyz** [comment]
Ah, makes sense. I must have overlooked that. will close this one out
