### ISSUE TITLE
Chromium requires GCC-only library (libatomic)

### ISSUE THREAD

**Issue by f1nniboy** [12101111/overlay#19]
Hey, I was trying to compile Chromium (93.0.4567.0) but it failed because it requires libatomic, a GCC-only library.

Build Log: http://0x0.st/-fdw.log
`emerge --info`: https://0x0.st/-fdx.txt

**Comment by 12101111** [comment]
You should set `-rtlib=compiler-rt` in `LDFLAGS` if you are using clang.

**Comment by f1nniboy** [comment]
Still the same issue.

**Comment by 12101111** [comment]
This patch should remove libatomic requirement:
https://github.com/12101111/etc-portage/blob/master/patches/www-client/chromium/remove-libatomic.patch

**Comment by f1nniboy** [comment]
Thanks. That patch fixed it. I now have another adventure because I want to remove all my X libraries and Chromium still requires X libraries.
