### ISSUE TITLE
sys-libs/musl-legacy-compat seems to cause build failures for gnulib packages?

### ISSUE THREAD

**Issue by KevinThomas0** [12101111/overlay#22]
I was getting errors trying to compile wget, tar, findutils, and bison, and they were all failing with similar errors (usually the error was something like: `undefined reference to 'error'`). I got help online and was told /usr/include/sys/cdefs.h doesn't normally exist on musl systems, and that's what was causing these build errors, as it's probably confusing gnulib. I removed libreoffice (and in turn, sys-libs/musl-legacy-compat), and I was able to build those packages fine again. So maybe this package could be causing problems?

**Comment by capezotte** [comment]
Guess this can be closed, `error.h` was the source of the errors and it was dropped in musl-legacy-compat-3. I can build both coreutils and LibreOffice just fine.
