### ISSUE TITLE
dev-lang/deno 1.32.4 is latest

### ISSUE THREAD

**Issue by tunerooster** [12101111/overlay#26]
dev-lang/deno 1.32.4 is the latest release, but the current ebuild in this repo is for 1.28.0

It would be greatly appreciated if idev-lang/deno-1.32.4.ebuild could be added.

MANY THANKS!!!

**Comment by 12101111** [comment]
https://github.com/12101111/overlay/commit/5bcb82ae0efbb34858ba061edfb71a665ce5b2dd
