### ISSUE TITLE
llvm-libgcc needs llvm-libunwind with USE="+static-libs" 

### ISSUE THREAD

**Issue by stefson** [12101111/overlay#29]
hey, I just noticed your llvm-libgcc ebuild doesn't pull in llvm-libunwind with the static-libs useflag. 

If it is not enabled, llvm-libgcc ebuild will fail to find `/usr/lib/libunwind.a`

**Comment by LinuxUserGD** [comment]
Fixed by 65de21f?

**Comment by stefson** [comment]
Ah yeah, that looks good to me.
