### ISSUE TITLE
"xapian.h: No such file or directory" when install goldendict.

### ISSUE THREAD

**Issue by buddhiko1** [12101111/overlay#31]
I have to install "dev-libs/xapian" manually to fix this bug.  
Does this library have to be included in the ebuild?

**Comment by shenlebantongying** [comment]
>  Does this library have to be included in the ebuild?

Yes, the old backend was removed. This shouldn't be an option but rather a hard dependency now.

https://github.com/12101111/overlay/blob/eaa1e662f576a69f3f2403765b0528977bd3aa3f/media-libs/libzim/libzim-9.1.0.ebuild#L20

**Comment by 12101111** [comment]
Thanks.

https://github.com/12101111/overlay/commit/56b441b05d76758424c54f9855a16c0f36df7623
