### ISSUE TITLE
Does your vscode ebuild use prebuilt binaries?

### ISSUE THREAD

**Issue by PF4Public** [12101111/overlay#5]
Like the title says. Does your ebuild recompile vscode from source, like in atom overlay, or is just using prebuilt binaries from Microsoft?

**Comment by 12101111** [comment]
There are two USE flags, `system-electron` and `system-ripgrep` that control whether not to use prebuilt electron (It takes a long time to compile) and ripgrep (It need rust to compile).
Anything else are compiling from source code using the [offical method](https://github.com/microsoft/vscode/wiki/How-to-Contribute)

**Comment by PF4Public** [comment]
Would you recommend using it on a daily basis or it still needs some more work?
